version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    platform: linux/amd64
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: testDb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: db_user
      PMA_PASSWORD: db_user_pass
    ports:
      - '8080:80'

volumes:
  db_data:
